### ISSUE TITLE
Things that maybe be changed or broken or missing

### ISSUE THREAD

**Issue by lefty55104** [wpa11yday/wpaccessibilityday#10]
- [x]  The current site has a checkmark as the bullet image for all unordered lists and it's not showing on all pages, for example: 
https://staging.wpaccessibility.day/people/nicolas-steenhout/ 
https://staging.wpaccessibility.day/sessions/keynote/
https://staging.wpaccessibility.day/thank-you-for-spending-the-day-with-us/
- [x]  When on the main people page (https://staging.wpaccessibility.day/wpad-people/), all of the subnav items have the purple border instead of what should probably be just the top level item.
- [x]  The copyright on mobile doesn't break to two lines.

**Comment by joedolson** [comment]
I'm not a big fan of custom bullet points, so that's a thumbs up from me!
