### ISSUE TITLE
Image alignment off in admin block editor

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#113]
All of the images are shifted left in the editor, even when set to alignnone or aligncenter. The captions are also given a very tiny width.

<img width="903" alt="Screenshot in the editor" src="https://github.com/user-attachments/assets/6a37260a-6ac9-4b95-9ac9-907d0f0f3038">

Here's an [example blog post.](https://2024.wpaccessibility.day/?p=4772&preview=true&_thumbnail_id=4773)

They look fine on the front end, so not emergent.

**Comment by joedolson** [comment]
This is coming from WP Accessibility; it's due to a difference in editor styles between theme's with a `theme.json` and themes without. Will fix there.

**Comment by joedolson** [comment]
Turns out it was more complicated than that; it was impacted by WP Accessibility, but was *also* a problem from the theme.

**Comment by joedolson** [comment]
Probably keep an eye out for consequences; as far as I can tell, the styles I removed from the theme were always being overwritten; but I could have missed something somewhere.

**Comment by amberhinds** [comment]
Will do, thank you
