### ISSUE TITLE
Duotone filters not working on volunteers page

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#119]
https://github.com/wpa11yday/wpaccessibilityday/blob/7a3bd34cbd1af155cef3f9a01613aef6221d6853/functions.php#L773

I'm not sure why this isn't working properly, but the volunteers page appears to not have the duotone filters: https://2024.wpaccessibility.day/about/volunteers/

It works on 2023 though... https://2023.wpaccessibility.day/about/volunteers/

**Comment by joedolson** [comment]
Fixed. The shortcode needs to be wrapped in a group with class '.organizers', which wasn't retained when the page was broken up into two separate volunteer sections.
