### ISSUE TITLE
Footer columns not floating as expected

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#12]
https://2023.wpaccessibility.day/news/ (or any page).

I think it's because there's a grid set on #footer-sidebar-columns, but the widgets from the columns are not in containers. 

<img width="1409" alt="Screen Shot of footer sidebar columns grid" src="https://user-images.githubusercontent.com/13153456/229680350-26f39310-1f07-4eaf-afd3-506ba725d2a9.png">

**Comment by joedolson** [comment]
Can you clarify what the expected behavior is? The aside has a class 'footer-columns-2', so this matches the expectation from the code; but I'm guessing this is supposed to be three columns?

**Comment by amberhinds** [comment]
Looks like you figured it out. Sorry I was away.
