### ISSUE TITLE
Replace hardcoded event date & social nav in header with widget region

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#15]
https://github.com/wpa11yday/wpaccessibilityday/blob/ca5d961c756c0a4ec7e44282a05b66f07f689ead/src/wp-a11y-day/header.php#L51

In an ideal world, I think this would be a widget area.  I don't know that we're always going to want the next upcoming event on the main website.

Also, it would be easiest for non-technical volunteers if there was a shortcode in the plugin that would allow the event start and end times to be edited in the conference schedule settings.  I'll open a separate to-do for that.

**Comment by lefty55104** [comment]
@joedolson I can create a widget area for this. Will the widget area just have a text widget with the text part added or should I create a shortcode for this? 

If shortcode, how would you want to handle the datetime in the shortcode? Individual attributes for each item (year, month, day, hour, minute)? Something else? Or leave it off for now?

**Comment by joedolson** [comment]
Just create it as a widget area; we'll populate with a text widget for now; I still need to spec what the widget will actually do, but that won't be part of the theme, it'll be in the plugin.

**Comment by lefty55104** [comment]
@joedolson I have a widget region for just the event date for now in the "header-widget-regions" branch. I haven't been able to test it, so I don't know if it needs any additional styling.

Did you also want me to replace the social nav with its own? There's that nav element that wouldn't be added if the menu widget was used in the new event date widget region.

**Comment by joedolson** [comment]
I don't think we need to replace the social nav; there's no reason that can't remain assigned as it is, I think. @amberhinds Do you have an opinion here?

**Comment by amberhinds** [comment]
I think leave it there.

**Comment by joedolson** [comment]
Great - then I think this can be closed. Thanks @lefty55104!
