### ISSUE TITLE
Nav button needs style fixes

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#31]
<img width="752" alt="Screen Shot 2023-08-03 at 3 57 02 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/c6036a14-16a9-4095-b5c1-42f1e0986549">

**Comment by joedolson** [comment]
Whaddaya mean? Looks great. I like black on black.

**Comment by joedolson** [comment]
Change the class to `wp-block-button` so it can inherit the same way as other blocks do. (.button is a link class, so it messes with some descendancy; if you use `wp-block-button`, this will be closer to what we want to start.)
