### ISSUE TITLE
Add styles for .decoration-left and .decoration-right

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#34]
This would be added to heading tags to add this decorative element and position it left or right.
<img width="603" alt="Screen Shot 2023-08-03 at 4 27 33 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/1c9b092c-c432-49ce-95da-29fe7959d5dd">
It might also need to position the heading differently from a margin standpoint?

.decoration-left is on the home page currently.

**Comment by joedolson** [comment]
Can you put the decoration on the group instead of the heading? Ideal would be if the group had `wp-block-group align-wide decoration-left`

**Comment by amberhinds** [comment]
Yes, moved to the group.
