### ISSUE TITLE
Add styles for groups with .stylized-2col-section

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#35]
This is for this section in the home page design.
<img width="1856" alt="Screen Shot 2023-08-03 at 4 59 52 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/7e6411b6-dd49-4699-94cd-5bbd9090c908">

Here is the SVG file for the background. I stretched the squares to 1920px wide for larger monitors.
![abstract-rectangles-background](https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/5d1c0e43-0e50-42d1-bcc6-eee05c48b227)

I only put the .stylized-2col-section class on the group block. I'm hoping we can target all the other styles based on that, but let me know if we need classes on the columns too.

**Comment by amberhinds** [comment]
Hold, that SVG didn't export right. I'll have to figure out why...

**Comment by joedolson** [comment]
Yeah, it definitely didn't. It's up using that SVG as a placeholder, though; works pretty well, other than the icons!

**Comment by amberhinds** [comment]
OK, I think I figured out how to convert the font awesome icons to images rather than fonts. Can you try the one I just posed above?

**Comment by joedolson** [comment]
Yep. That works!
