### ISSUE TITLE
Sponsors single needs styles and some rearranging of elements to fit the design.

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#40]
https://staging.wpaccessibility.day/sponsors/codegeek/

**Comment by joedolson** [comment]
Do you think we should set a background behind logos, or leave transparent logos as they are?

**Comment by joedolson** [comment]
Do you have an example with swag?

**Comment by amberhinds** [comment]
I think it should be a white square for the logo and the logo should be positioned in it.

I can get a Swag example, one moment.

**Comment by amberhinds** [comment]
Gravity Forms has Swag Added - https://staging.wpaccessibility.day/sponsors/gravity-forms/

**Comment by joedolson** [comment]
Yep. On it.
