### ISSUE TITLE
Sponsors website link styled as a button needs display:block

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#49]
<img width="349" alt="Screen Shot 2023-08-04 at 12 31 41 AM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/7ac32ff5-6867-4b47-9cde-e7f5643c13f2">

Adding display:block will fix this.

**Comment by joedolson** [comment]
This is probably true of all button links.
