### ISSUE TITLE
Adjust Tab Order (Remove forced focus on email subscribe)

### ISSUE THREAD

**Issue by Braceomatic88** [wpa11yday/wpaccessibilityday#54]
The Email Address field in the Email Subscribe box forces focus on page visit, causing the skip links, logo and navigation to be skipped over in the tab order

**Comment by amberhinds** [comment]
@Braceomatic88 what browser and os? I'm not getting itout of order in Chrome or Firefox.

**Comment by Braceomatic88** [comment]
i was getting it on Chome Version 115.0.5790.114 on macOS Big Sure Version 11.7.6

**Comment by joedolson** [comment]
I'm also unable to reproduce this.

**Comment by Braceomatic88** [comment]
I can take a screen record for you guys, I'm not sure why I'm getting it

[Video grab linked here](https://www.dropbox.com/scl/fi/0rh9b3xd6lf5x4ws0prpm/Screen-Recording-2023-08-08-at-4.49.06-PM.mov?rlkey=pe0hklt8qkk2men3kimb5myga&dl=0)

**Comment by joedolson** [comment]
Is that your password manager auto filling the input? What happens if you turn off your password manager?

**Comment by Braceomatic88** [comment]
Turns out, yes. That is exactly what was happening. Sorry about that

**Comment by joedolson** [comment]
Not a problem! Thanks for following up. If a user has a tool that changes focus behavior for them, that's something we shouldn't override, so I think we're good to go. Thanks!
