### ISSUE TITLE
Margin above "About XYZ" H2 on people single should be 80px

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#60]
Current:
<img width="1170" alt="Screen Shot 2023-08-07 at 7 38 23 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/b77ce1bc-c403-46af-9edc-c9fc974e2cff">
Design:
<img width="734" alt="Screen Shot 2023-08-07 at 7 38 57 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/fdc2519b-48b2-48d6-9722-25d83c41feae">

**Comment by joedolson** [comment]
This is actually kind of tricky, because of the columns. The header background doesn't have any relationship to the content, so it's all very approximate. I think we just have to accept that it's going to vary, or I can do a custom template so that we change the content structure.

**Comment by joedolson** [comment]
I had to add a custom template to resolve https://github.com/wpa11yday/conference/issues/48, so figured I might as well resolve this, as well.
