### ISSUE TITLE
Empty field label on Gravity Forms front end log-in form

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#61]
Here's the code:
```
<div id="field_0_3" class="gfield gfield--type-remember_me field_sublabel_below gfield--no-description field_description_below hidden_label gfield_visibility_visible" data-js-reload="field_0_3"><label class="gfield_label gform-field-label screen-reader-text gfield_label_before_complex"></label><div class="ginput_container ginput_container_checkbox"><div class="gfield_checkbox" id="input_3"><div class="gchoice gchoice_3">
						<input class="gfield-choice-input" name="input_3.1" type="checkbox" value="1" id="choice_3">
						<label for="choice_3" id="label_3">Remember Me</label>
					</div></div></div></div>
```
<img width="1688" alt="Screen Shot of the field on the page and code in dev tools" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/e9b84e0e-c37b-4e63-aab3-0e3ec3053eda">

You have to look at this page not logged in: https://2023.wpaccessibility.day/log-in/

I think this is an orphaned label and may not be an issue, but let me know if I should raise it with Gravity Forms.

**Comment by alexstine** [comment]
In my testing, not an issue in Chrome or Firefox.

That heading level 3 likely doesn't need to be there though, just above the username field.

**Comment by amberhinds** [comment]
Great. I hid the form title (the H3 you saw).

Shall I close this issue?

**Comment by alexstine** [comment]
👍
