### ISSUE TITLE
Side scroll (1401px to 961px wide)

### ISSUE THREAD

**Issue by lefty55104** [wpa11yday/wpaccessibilityday#64]
Adding `.entry-header svg:not(.entry-header-subscribe svg) { width: 50% }` fixes it, or I guess some kind of overflow hidden on a wrapping element if you wanted to keep the height the same.

**Comment by joedolson** [comment]
I'm not seeing this issue right now; it's not impossible it got fixed by some other PR before I looked at this issue. If you could confirm, and provide more detail if it's still there, that would be great.

**Comment by lefty55104** [comment]
Here's a quick video: https://glq6azuah5.vmaker.com/record/V7Qb3SAALxvDes77

**Comment by joedolson** [comment]
Got it. Thanks!
