### ISSUE TITLE
Duotone filters suddenly not working 

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#66]
I'm not sure why, but the duotone filters over people's images appear not to be working anymore. They were working a few hours ago.

This can be seen on:

- [The Organizers Page](https://2023.wpaccessibility.day/about/organizers/)
- [The Speakers Page](https://2023.wpaccessibility.day/wpad-people/speakers/)

I see unfiltered images in Chrome and Firefox on Mac and Edge on Windows.
<img width="1167" alt="Screen Shot 2023-08-08 at 11 10 37 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/9f97aa6b-15b4-4490-8ea7-60b40608d328">

The CSS appears to be there, and there's not a clear reason why it's no longer working.

**Comment by joedolson** [comment]
First thing that comes to mind is WP 6.3; it released today, so the timing
is right.

**Comment by amberhinds** [comment]
https://core.trac.wordpress.org/ticket/59017#ticket

**Comment by joedolson** [comment]
Temporary fix with a rollback to 6.2.2; but I'll probably use the suggestion in https://core.trac.wordpress.org/ticket/59017#comment:5 to set these back up. I suspect that this won't be changed in core, it'll just end up getting some documentation on how to continue to use these.
