### ISSUE TITLE
Sponsors page logos & sponsor type headings in dark mode

### ISSUE THREAD

**Issue by joedolson** [wpa11yday/wpaccessibilityday#68]
Most logos we have are designed for light mode only, so we need to apply backgrounds on those. 

![image](https://github.com/wpa11yday/wpaccessibilityday/assets/1686451/46be96ba-3169-454b-ad13-9c3d4641cc72)

**Comment by amberhinds** [comment]
Do they need backgrounds in the image or can it be added with CSS?

This is me hoping I don't have to Photoshop logos every year.🤞

**Comment by joedolson** [comment]
This can be 100% CSS. Anything with a solid background should be clearly visible. (Or, at least as visible as it was to begin with.)
