### ISSUE TITLE
Why don't people show up in the block editor link suggestions?

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#76]
I feel like people posts used to show up here. Now they don't. Is this a core bug?
<img width="467" alt="Screen Shot 2023-08-19 at 11 58 11 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/c7f30d65-556c-4b5d-a80a-31e73bfd5686">

**Comment by joedolson** [comment]
Ah - it's because we switched to using the classic editor by disabling the
REST api for custom post types. The link suggestions use the API.

We'll need to do that in a different way.

**Comment by amberhinds** [comment]
Thank you!!
