### ISSUE TITLE
Dark Mode Select Focus Color

### ISSUE THREAD

**Issue by jeryj** [wpa11yday/wpaccessibilityday#77]
In Dark Mode, when a select element is focused, it has black text on a black background. Adding a color to `select:focus` in the inspector seems to fix it, but I didn't have the dev environment set-up to fully test it:

```
select:focus {
  color: white;
}
```

![Focusing country select field turns black text on white background into black text on black background](https://github.com/wpa11yday/wpaccessibilityday/assets/967608/b2d9502a-5bdb-48b7-b7de-59c06657069d)

**Comment by joedolson** [comment]
Thanks for catching that, Jerry! We'll get right on it!
