### ISSUE TITLE
Dark mode color contrast issues on the Gravity Forms user activation page

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#80]
![381303002_859954112179946_4850067143209974289_n](https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/d6b0d24b-b34f-4604-8101-fc62e1a116bd)

The username and password labels don't switch to white in dark mode.

**Comment by joedolson** [comment]
Do you know a way to get to that page other than registering?

**Comment by joedolson** [comment]
The only place that span.h3 occurs in the plugin directory is in `activate.php`, and I've deleted it from that file. I am, however, still seeing it on the front-end; but I have to assume that this is some uncleared cache, even though I can't figure out what it could be.
