### ISSUE TITLE
Can there be a setting somewhere that allows us to change the color of the background at the top of the home page?

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#87]
I think it would be nice if this could vary by event.
<img width="1477" alt="Screenshot 2024-02-04 at 9 27 35 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/4a030ffb-765f-4938-8f34-b8d0560b606b">

I tried changing the page template and it didn't quite work. Can we have the existing CSS for the home page respond to the page template?

<img width="1474" alt="Screenshot 2024-02-04 at 9 30 10 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/a1f1a302-74f3-43c3-bfd0-e551b147d527">

**Comment by amberhinds** [comment]
Also, if you need me to make different color versions of that line of people, I can.

**Comment by joedolson** [comment]
Done! Applied on 2024. 

No need for other versions of the SVG; we're controlling those colors in CSS.
