### ISSUE TITLE
Move styles from the customizer into the theme

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#9]
😳 I put styles in the customizer right before the event. These should probably be moved into the theme or plugin as applicable.

**Comment by joedolson** [comment]
All styles from theme.css, style.css, and the customizer have been combined and some minor optimizing done. Test site with the merged CSS is in place currently at staging.wpaccessibility.day; it's a clone of 2022.wpaccessibility.day. This also has the updated version of the scheduler plugin, so we can verify everything works as expected.

**Comment by joedolson** [comment]
Seems to be fine; closing. As we develop the new design, we may noticing things, but there are always changes to be made in that process, so no concerns.
