### ISSUE TITLE
Remove arrow button style option

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#91]
<img width="312" alt="Screenshot button settings panel in the editor" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/5c3b1c07-f5a2-4e8f-abbf-1e42f3b76438">

Our theme only styles the "Fill" and "underline" style buttons. There are no styles for the "arrow" style button, so this should be removed as an option.

**Comment by joedolson** [comment]
We do have styles for the arrow button; they could probably stand to be more fully fleshed out, but they do exist.

![image](https://github.com/wpa11yday/wpaccessibilityday/assets/1686451/50e43356-2429-4c3f-9f40-5f8aa418fdf8)

**Comment by amberhinds** [comment]
That doesn't match our designs though so I don't think people should use it. We don't have any rounded buttons anywhere in the designs and the "underline" style button has an arrow on it.

**Comment by joedolson** [comment]
Ah, so what we've actually done is created two separate patterns that are super similar in name, so we can maximize confusion. 

Should the underline pattern actually be called arrow?

**Comment by amberhinds** [comment]
I'd be fine with renaming underline, as long as I don't have to fix all
existing buttons. 😅

I don't think we created the arrow style. I'm pretty sure that wasn't there
last year and is showing up because of a change in core.
