### ISSUE TITLE
Strange Footer Nav Behavior on 2024 site

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#94]
I saw some really strange behavior while editing nav menus on 2024. I've never seen this before. Here's a video: https://app.screencastify.com/v3/watch/vZnCjBEMMD3cR8kqkws6

Any ideas what caused this?

**Comment by amberhinds** [comment]
It seems like I can't even remove these - there's now two of every menu item in the editor but only one on the front end:
<img width="619" alt="Screenshot 2024-02-10 at 12 40 22 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/fc1419db-811a-40af-bf0f-8e2c4ce29a16">
<img width="237" alt="Screenshot 2024-02-10 at 12 40 46 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/5d21acc5-6dc5-440a-8383-32a70ddf2c23">

https://2024.wpaccessibility.day/wp-admin/nav-menus.php?action=edit&menu=8

I have this console error:
<img width="384" alt="Screenshot 2024-02-10 at 12 41 50 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/ae7c043a-1711-430b-b4f9-d79a5ee3de39">

I tested deactivating Matomo since I had just activated it and ruled that out as a plugin conflict.

**Comment by joedolson** [comment]
Figured out the menu bug. It's my fault; the search and replace for 2023 created this problem. It changed the post dates of menu items to the future, which was fine until they were edited - but then editing caused them to change status to future. Which made them visible in the admin but not on the front end. 

I'm bulk changing the dates & statuses of menu items.

**Comment by amberhinds** [comment]
Oh, interesting. 

Probably also a good reason for why everything shouldn't be a post type...

**Comment by joedolson** [comment]
Not a problem for content, because content passes dates when it's updated; but menus are theoretically undated, so they don't send that information when edited.
