### ISSUE TITLE
Make Gravity Forms PDFs folder not publicly accessible on 2024 site

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#95]
Saw this message in Gravity Forms: Your generated PDFs folder is publicly accessible. This could allow anyone to view your PDFs. [Click here to learn how to make this folder private.](https://forgravity.com/documentation/fillable-pdfs/protecting-your-pdfs/)

Should probably be addressed before sponsors start signing contracts.

**Comment by joedolson** [comment]
This warning is still appearing, but the folder is *not* publicly accessible. Perhaps a flaw in how the plugin detects folder availability? Not going to prioritize this at the moment. We're fine.
