### ISSUE TITLE
Speaker Submission Form Updates for 2024

### ISSUE THREAD

**Issue by Braceomatic88** [wpa11yday/wpaccessibilityday#97]
Field: Talk Format
- Change “Panel Discussion (50 minutes with Q&A throughout)” to “Panel Discussion of 3 or more co-presenters (50 minutes with Q&A throughout)”
*Hoping this would help to clarify that 2 people presenting is not truly a panel

Field: At which times are you available to present?
- Change “September 27th” to “October 9th”
- Change “September 28th” to “October 10th”

**Comment by joedolson** [comment]
Updated on 2024 site.
